<a href="https://colab.research.google.com/github/doudi0101/ML-TPs/blob/main/RL_Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Step -1: Install the dependencies on Google Colab

In [ ]:
!pip install numpy
!pip install openai-gym

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement openai-gym (from versions: none)
ERROR: No matching distribution found for openai-gym


In [ ]:
#import the required libraries.
import numpy as np
import gym
import random

In [ ]:
#create the environment usign OpenAI Gym
env = gym.make("FrozenLake-v0")

## Step 2: Create the Q-table and initialize it

In [ ]:
action_size = env.action_space.n
state_size = env.observation_space.n

print(f"Action Space : {action_size} | State Space: {state_size}")

Action Space : 4 | State Space: 16


In [ ]:
qtable = np.zeros((state_size, action_size))
print(qtable.shape)

(16, 4)


## Step 3: Create Required Hyperparameters

In [ ]:
total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob

## Step 4 : Q-Learning Algorithm

In [ ]:
# List of rewards
rewards = []

#until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        #Choose an action a in the current world state (s)
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * \
                                                        (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode) 

    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.4792666666666667
[[2.30621070e-01 5.37462276e-02 8.34725296e-02 7.87303625e-02]
 [9.77398828e-03 2.84992619e-03 9.20890988e-03 1.09950460e-01]
 [4.98454714e-02 6.14721951e-03 6.60912284e-03 6.18215953e-02]
 [8.88693500e-04 5.78675933e-05 6.56650237e-03 5.16960428e-02]
 [2.01331576e-01 5.81651699e-02 1.79999992e-02 1.66346441e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.32467447e-04 1.73721266e-04 1.18002739e-05 3.95411301e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.06682895e-02 2.17673490e-02 2.49951456e-02 2.80578056e-01]
 [3.40201004e-02 1.90882632e-01 1.62581566e-02 2.80204972e-02]
 [3.73504459e-02 1.94842782e-04 3.32070334e-03 1.25660367e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.86415244e-02 2.49454662e-02 8.46582517e-01 1.60891957e-01]
 [1.31725738e-01 9.91996128e-01 1.80085049e-01 2.33065762e-01]
 [0.00000000e+00 0.

In [ ]:
for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 46
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 39
****************************************************
EPISODE  2
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 38
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 91
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 56
